trigger:
  branches:
    include:
      - master
  tags:
    include:
      - '*'

pr:
  autoCancel: true # Cancels a PR build if a new commit comes in on the same branch
  branches:
    include:
      - '*'

jobs:
- job: BuildAndTest
  displayName: Build and test
  
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    buildConfiguration: 'Release'

  steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'Build $(buildConfiguration)'
  - script: dotnet test
    displayName: 'Run unit tests'

- job: BuildAndPushImage
  displayName: Build and Push image
  dependsOn: BuildAndTest
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  pool:
    vmImage: 'ubuntu-latest'
  
  steps:
  - task: Docker@2
    displayName: Login to Container Registry
    inputs:
      command: login
      containerRegistry: CDSDockerHub
  - task: Docker@2
    inputs:
      command: buildAndPush
      repository: cdssnc/hello-esdc-api
      tags: latest
      Dockerfile: src/HelloESDC.API/Dockerfile