trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: Docker@2
  displayName: Login to Container Registry
  inputs:
    containerRegistry: 'CDSDockerHub'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'CDSDockerHub'
    repository: 'cdssnc'
    command: 'buildAndPush'
    Dockerfile: 'src/HelloESDC.API/Dockerfile'