trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: Docker@2
  displayName: Login to Container Registry
  inputs:
    command: login
    containerRegistry: CDSDockerHub
- task: Docker@2
  inputs:
    command: buildAndPush
    repository: cdssnc/hello-esdc-api
    Dockerfile: src/HelloESDC.API/Dockerfile