trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: Docker@2
  inputs:
    containerRegistry: 'HelloESDCRegistry'
    command: 'login'
    
- task: Docker@2
  inputs:
    containerRegistry: 'HelloESDCRegistry'
    repository: 'hello-esdc-api'
    command: 'buildAndPush'
    Dockerfile: 'src/HelloESDC.API/Dockerfile'
    buildContext: 'src/HelloESDC.API'