version: '3.4'

networks:
  hello-esdc-dev:
    driver: bridge 

services:
  hello-esdc-api:
    image: hello-esdc-api:latest
    depends_on:
      - "postgres_image"
    build:
      context: ./src/HelloESDC.API
      dockerfile: Dockerfile.development
    ports:
      - "5000:5000"
    volumes:
      - ./src/HelloESDC.API:/app
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=helloesdc;username=helloesdc;password=helloesdc"
    networks:
      - hello-esdc-dev  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./database/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "helloesdc"
      POSTGRES_PASSWORD: "helloesdc"
      POSTGRES_DB: "helloesdc"
    networks:
      - hello-esdc-dev
volumes:
  db_volume: